FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        iputils-ping \
        vim && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY /tcm/Tcm /app/
CMD ["./Tcm"]
