# Use a newer Ubuntu image
FROM ubuntu:24.04




WORKDIR /app
COPY /dashboard/Dashboard /app/

CMD ["./Dashboard"]
# Install Boost runtime dependencies and stdlib
RUN apt-get update && apt-get install -y \
    libboost-system-dev \
    libboost-json-dev \
    libstdc++6 \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*